name: Flask Unit Tests

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add any requirements if necessary

      - name: Start Flask app
        run: |
          gunicorn -b 0.0.0.0:5000 -w 2 app:app &  # Start Flask app in the background

      - name: Run unit tests
        run: |
          python -m unittest discover Test  # Adjust based on your test setup
