name: Flask Unit Tests

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add any requirements if necessary

      - name: Start Streamlit app
        run: |
          streamlit run app.py &

      - name: Wait for Streamlit to start
        run: sleep 10

      - name: Start Flask app
        run: |
          gunicorn -b 0.0.0.0:5000 -w 2 app:app --log-file=gunicorn.log &
          sleep 10

      - name: Check Gunicorn logs
        run: cat gunicorn.log

      - name: Run unittest tests
        run: |
          python -m unittest discover -s Test -p 'test_*.py'
